from typing import Any

def cudaMallocHost(size: int) -> Any: ...
def cudaFreeHost(ptr: Any) -> None: ...
def cudaMalloc(size: int) -> Any: ...
def cudaFree(ptr: Any) -> None: ...
def cudaStreamCreate() -> Any: ...
def cudaMemcpyAsync(
    dst: Any, src: Any, size: int, kind: int, stream: Any
) -> Any: ...
def cudaStreamSynchronize(stream: Any) -> Any: ...
def cudaStreamDestroy(stream: Any) -> Any: ...

cudaError_t: Any
cudaMemcpyKind: Any
